We first need to download Geocoder

In [ ]:
import sys
!{sys.executable} -m pip install pandas tqdm

Requirement already satisfied: pandas in c:\users\terzi\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\terzi\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\terzi\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\terzi\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: colorama in c:\users\terzi\appdata\local\programs\python\python312\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\terzi\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, geographiclib, geopy

   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [geographiclib]
   -------------------------- ------------- 2/3 [geopy]
   -------------------------- ------------- 2/3 [geopy]
   -------------------------- ------------- 2/3 [geopy]
   -------------------------- ------------- 2/3 [geopy]
   -------------------------- ------------- 2/3 [geopy]
   -------------------------- ------------- 2/3 [geopy]
   ---------------------------------------- 3/3 [geopy]

Successfully installed geographiclib-2.1 geopy-2.4.1 tqdm-4.67.3

  WARNING: The script tqdm.exe is installed in 'c:\Users\terzi\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Libraries

In [22]:
import pandas as pd
import os

In [12]:
import pandas as pd

df = pd.read_csv("ExportBuildings.csv")

df.head()

,Building_Name,Campus,Address
0,110 SOUTH ADAMS STREET,MONROE PARK CAMPUS,110 SOUTH ADAMS STREET
1,1109 WEST MARSHALL ST,MONROE PARK CAMPUS,1109 WEST MARSHALL ST
2,1235 W. BROAD ST RETAIL 1,MONROE PARK CAMPUS,1235 W. BROAD ST RETAIL 1
3,"125 S. HARRISON, SOCCER LOCKER ROOM",MONROE PARK CAMPUS,125 SOUTH HARRISON STREET
4,1310-1312 WEST MAIN ST,MONROE PARK CAMPUS,1310-1312 WEST MAIN STREET

Checking the columns

In [13]:
df.columns

Index(['Building_Name', 'Campus', 'Address'], dtype='str')

Looking for missings to fix

In [14]:
df[["Building_Name", "Campus", "Address"]].head(15)

,Building_Name,Campus,Address
0,110 SOUTH ADAMS STREET,MONROE PARK CAMPUS,110 SOUTH ADAMS STREET
1,1109 WEST MARSHALL ST,MONROE PARK CAMPUS,1109 WEST MARSHALL ST
2,1235 W. BROAD ST RETAIL 1,MONROE PARK CAMPUS,1235 W. BROAD ST RETAIL 1
3,"125 S. HARRISON, SOCCER LOCKER ROOM",MONROE PARK CAMPUS,125 SOUTH HARRISON STREET
4,1310-1312 WEST MAIN ST,MONROE PARK CAMPUS,1310-1312 WEST MAIN STREET
5,1607 SHERWOOD AVE,OFF-CAMPUS,1607 SHERWOOD AVE
6,1609 SHERWOOD AVE,OFF-CAMPUS,1609 SHERWOOD AVE
7,201 N. BELVIDERE STREET,MONROE PARK CAMPUS,201 NORTH BELVIDERE STREET
8,205 E. BROAD ST,0,205 E. BROAD ST
9,205 E. BROAD ST,MONROE PARK CAMPUS,205 E. BROAD ST
10,"205 W. FRANKLIN ST #3, 3 FL",MONROE PARK CAMPUS,"205 W. FRANKLIN ST #3, 3 FL"
11,22 N LAUREL ST,MONROE PARK CAMPUS,22 N LAUREL ST
12,2303 N. PARHAM ROAD,0,2303 N. PARHAM ROAD
13,2303 N. PARHAM ROAD,OFF-CAMPUS,NaN
14,2303 N. PARHAM ROAD,OFF-CAMPUS,2303 N. PARHAM ROAD

Missing addresses

In [16]:
missing_addr = df[df["Address"].isna() | (df["Address"].astype(str).str.strip() == "")]

missing_addr.head(30)

                                 Building_Name              Campus Address
13                         2303 N. PARHAM ROAD          OFF-CAMPUS     NaN
15                         2601 HERMITAGE ROAD  MONROE PARK CAMPUS     NaN
19                         2901 HERMITAGE ROAD          OFF-CAMPUS     NaN
42                      ADULT OUTPATIENT (AOP)          MCV CAMPUS     NaN
50                              BIOTECH CENTER                 NaN     NaN
61                               CABANISS HALL                 NaN     NaN
76                     CLINICAL SUPPORT CENTER                 NaN     NaN
79            COMMONWEALTH OF VIRGINIA (STEAM)                 NaN     NaN
80            COMMONWEALTH OF VIRGINIA (STEAM)          OFF-CAMPUS     NaN
82                      CRITICAL CARE HOSPITAL                 NaN     NaN
91                                      EE LOT  MONROE PARK CAMPUS     NaN
94                                  EE LOT EXT  MONROE PARK CAMPUS     NaN
96                           EGYPTIAN BUILDING                 NaN     NaN
106                  FRANKLIN STREET GYMNASIUM  MONROE PARK CAMPUS     NaN
110                           GATEWAY BUILDING                 NaN     NaN
117                           GRACE ST. CENTER  MONROE PARK CAMPUS     NaN
127  HIBBS-GINTER-ANDERSON-SHAFER ST PLAYHOUSE  MONROE PARK CAMPUS     NaN
131                      HUNTON STUDENT CENTER                 NaN     NaN
135           INACTIVE & DEMOLISHED PROPERTIES       BOTH CAMPUSES     NaN
137                JAMES W. BLACK MUSIC CENTER  MONROE PARK CAMPUS     NaN
144            JONAH L. LARRICK STUDENT CENTER          MCV CAMPUS     NaN
156                              MAIN HOSPITAL                 NaN     NaN
176                         MONROE PARK CAMPUS  MONROE PARK CAMPUS     NaN
195       PROVOST-ANDERSON-SHAFER ST PLAYHOUSE  MONROE PARK CAMPUS     NaN
201                        RANDOLPH MINOR HALL          MCV CAMPUS     NaN
230                     SPORTS MEDICINE CENTER  MONROE PARK CAMPUS     NaN
237                                 STORMWATER                   0     NaN
243                  T. EDWARD TEMPLE BUILDING  MONROE PARK CAMPUS     NaN
270                               VDOT - ANNEX                   0     NaN
271                               VDOT - ANNEX          OFF-CAMPUS     NaN

Unique buildings

In [ ]:
bldgs = (
    df[["Building_Name", "Campus"]]
    .dropna(subset=["Building_Name"])
    .assign(Building_Name=lambda x: x["Building_Name"].astype(str).str.strip())
    .query("Building_Name != ''")
    .drop_duplicates(subset=["Building_Name"])
    .reset_index(drop=True)
)

bldgs.shape, bldgs.head(10)

bldgs.to_csv("vcu_unique_buildings.csv", index = False)

print("Export complete: vcu_unique_buildings.csv")

((255, 2),
                          Building_Name              Campus
 0               110 SOUTH ADAMS STREET  MONROE PARK CAMPUS
 1                1109 WEST MARSHALL ST  MONROE PARK CAMPUS
 2            1235 W. BROAD ST RETAIL 1  MONROE PARK CAMPUS
 3  125 S. HARRISON, SOCCER LOCKER ROOM  MONROE PARK CAMPUS
 4               1310-1312 WEST MAIN ST  MONROE PARK CAMPUS
 5                    1607 SHERWOOD AVE          OFF-CAMPUS
 6                    1609 SHERWOOD AVE          OFF-CAMPUS
 7              201 N. BELVIDERE STREET  MONROE PARK CAMPUS
 8                      205 E. BROAD ST                   0
 9          205 W. FRANKLIN ST #3, 3 FL  MONROE PARK CAMPUS)

Search Query to change the address

In [19]:

def make_query(row):
    name = row["Building_Name"]
    campus = str(row.get("Campus", "")).strip().lower()

    if "mcv" in campus:
        campus_hint = "VCU Medical Campus"
    elif "monroe" in campus:
        campus_hint = "VCU Monroe Park Campus"
    else:
        campus_hint = "Virginia Commonwealth University"
    
    return f"{name}, {campus_hint}, Richmond, VA"

bldgs["Query"] = bldgs.apply(make_query, axis=1)
bldgs[["Building_Name", "Campus", "Query"]].head(15)

,Building_Name,Campus,Query
0,110 SOUTH ADAMS STREET,MONROE PARK CAMPUS,"110 SOUTH ADAMS STREET, VCU Monroe Park Campus..."
1,1109 WEST MARSHALL ST,MONROE PARK CAMPUS,"1109 WEST MARSHALL ST, VCU Monroe Park Campus,..."
2,1235 W. BROAD ST RETAIL 1,MONROE PARK CAMPUS,"1235 W. BROAD ST RETAIL 1, VCU Monroe Park Cam..."
3,"125 S. HARRISON, SOCCER LOCKER ROOM",MONROE PARK CAMPUS,"125 S. HARRISON, SOCCER LOCKER ROOM, VCU Monro..."
4,1310-1312 WEST MAIN ST,MONROE PARK CAMPUS,"1310-1312 WEST MAIN ST, VCU Monroe Park Campus..."
5,1607 SHERWOOD AVE,OFF-CAMPUS,"1607 SHERWOOD AVE, Virginia Commonwealth Unive..."
6,1609 SHERWOOD AVE,OFF-CAMPUS,"1609 SHERWOOD AVE, Virginia Commonwealth Unive..."
7,201 N. BELVIDERE STREET,MONROE PARK CAMPUS,"201 N. BELVIDERE STREET, VCU Monroe Park Campu..."
8,205 E. BROAD ST,0,"205 E. BROAD ST, Virginia Commonwealth Univers..."
9,"205 W. FRANKLIN ST #3, 3 FL",MONROE PARK CAMPUS,"205 W. FRANKLIN ST #3, 3 FL, VCU Monroe Park C..."
10,22 N LAUREL ST,MONROE PARK CAMPUS,"22 N LAUREL ST, VCU Monroe Park Campus, Richmo..."
11,2303 N. PARHAM ROAD,0,"2303 N. PARHAM ROAD, Virginia Commonwealth Uni..."
12,2601 HERMITAGE ROAD,MONROE PARK CAMPUS,"2601 HERMITAGE ROAD, VCU Monroe Park Campus, R..."
13,2701-2709 HERMITAGE ROAD,OFF-CAMPUS,"2701-2709 HERMITAGE ROAD, Virginia Commonwealt..."
14,2801 A HERMITAGE ROAD,OFF-CAMPUS,"2801 A HERMITAGE ROAD, Virginia Commonwealth U..."