Packages to setup Pandas and Cleaning

In [1]:
import pandas as pd
import numpy as np

Loading of the Table into notebook in order to clean the N/As

In [14]:
df = pd.read_excel(
    "EDA for FY19-FY25.xlsx",
    sheet_name="Missing_Buildings",
    engine="openpyxl",
    keep_default_na=True,
    na_values=["", "#N/A", "#NA", "N/A", "NA"]
)

df.head()

,Provider,Type,Operator,Account,Customer_Type,Index,Bldg,Building_Name,Status,Campus,...,Amount_Due,Total_Usage,Reporting_Month,Svc_End_Date,UtiliTrak_Date,Svc_End_Date_Fixed,FY,Cost_per_kwh,Charge_Type,Bill_Type
0,DVP,Electric,NONE,004158739740,AUXILIARY,327510,0212,ACKELL RESIDENCE CENTER,ACTIVE,MONROE PARK CAMPUS,...,1488.72,1488.72,10.0,2018-04-01 00:00:00,NaN,2018-04-01,FY18,0.082341,Energy,Non-Credit
1,DVP,Electric,NONE,004158739740,AUXILIARY,327510,0212,ACKELL RESIDENCE CENTER,ACTIVE,MONROE PARK CAMPUS,...,1377.99,1377.99,11.0,2018-05-01 00:00:00,NaN,2018-05-01,FY18,0.086124,Energy,Non-Credit
2,DVP,Electric,NONE,004158739740,AUXILIARY,327510,0212,ACKELL RESIDENCE CENTER,ACTIVE,MONROE PARK CAMPUS,...,1249.39,1249.39,12.0,2018-06-01 00:00:00,NaN,2018-06-01,FY18,0.090274,Energy,Non-Credit
3,DVP,Electric,NONE,004234077677,E&G (UTILITIES),165201,0271,CATHEDRAL IV,ACTIVE,MONROE PARK CAMPUS,...,1991.43,1991.43,1.0,2017-07-01 00:00:00,NaN,2017-07-01,FY18,0.086209,Energy,Non-Credit
4,DVP,Electric,NONE,004234077677,E&G (UTILITIES),165201,0271,CATHEDRAL IV,ACTIVE,MONROE PARK CAMPUS,...,2408.10,2408.10,2.0,2017-08-01 00:00:00,NaN,2017-08-01,FY18,0.080270,Energy,Non-Credit

In [16]:
missing_rows = df[df["Building_Name"].isna()]

missing_rows

,Provider,Type,Operator,Account,Customer_Type,Index,Bldg,Building_Name,Status,Campus,...,Amount_Due,Total_Usage,Reporting_Month,Svc_End_Date,UtiliTrak_Date,Svc_End_Date_Fixed,FY,Cost_per_kwh,Charge_Type,Bill_Type
119,DVP,Electric,NONE,008505876295,AUXILIARY,323480,7006,NaN,NaN,NaN,...,9.63,9.63,11.0,2019-05-01 00:00:00,NaN,2019-05-01,FY19,NaN,Fixed,Non-Credit
343,DVP,Electric,NONE,000632349882,AUXILIARY,323480,7007,NaN,NaN,NaN,...,10.39,10.39,7.0,2018-01-01 00:00:00,NaN,2018-01-01,FY18,3.463333,Energy,Non-Credit
436,DVP,Electric,NONE,000632349882,AUXILIARY,323480,7007,NaN,NaN,NaN,...,10.39,10.39,8.0,2018-02-01 00:00:00,NaN,2018-02-01,FY18,3.463333,Energy,Non-Credit
473,DVP,Electric,NONE,000632349882,AUXILIARY,323480,7007,NaN,NaN,NaN,...,10.38,10.38,1.0,2017-07-01 00:00:00,NaN,2017-07-01,FY18,3.460000,Energy,Non-Credit
474,DVP,Electric,NONE,000632349882,AUXILIARY,323480,7007,NaN,NaN,NaN,...,10.39,10.39,2.0,2017-08-01 00:00:00,NaN,2017-08-01,FY18,3.463333,Energy,Non-Credit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit

In [18]:
valid = df[df["Building_Name"].notna()].copy()

valid

,Provider,Type,Operator,Account,Customer_Type,Index,Bldg,Building_Name,Status,Campus,...,Amount_Due,Total_Usage,Reporting_Month,Svc_End_Date,UtiliTrak_Date,Svc_End_Date_Fixed,FY,Cost_per_kwh,Charge_Type,Bill_Type
0,DVP,Electric,NONE,004158739740,AUXILIARY,327510,0212,ACKELL RESIDENCE CENTER,ACTIVE,MONROE PARK CAMPUS,...,1488.72,1488.72,10.0,2018-04-01 00:00:00,NaN,2018-04-01,FY18,0.082341,Energy,Non-Credit
1,DVP,Electric,NONE,004158739740,AUXILIARY,327510,0212,ACKELL RESIDENCE CENTER,ACTIVE,MONROE PARK CAMPUS,...,1377.99,1377.99,11.0,2018-05-01 00:00:00,NaN,2018-05-01,FY18,0.086124,Energy,Non-Credit
2,DVP,Electric,NONE,004158739740,AUXILIARY,327510,0212,ACKELL RESIDENCE CENTER,ACTIVE,MONROE PARK CAMPUS,...,1249.39,1249.39,12.0,2018-06-01 00:00:00,NaN,2018-06-01,FY18,0.090274,Energy,Non-Credit
3,DVP,Electric,NONE,004234077677,E&G (UTILITIES),165201,0271,CATHEDRAL IV,ACTIVE,MONROE PARK CAMPUS,...,1991.43,1991.43,1.0,2017-07-01 00:00:00,NaN,2017-07-01,FY18,0.086209,Energy,Non-Credit
4,DVP,Electric,NONE,004234077677,E&G (UTILITIES),165201,0271,CATHEDRAL IV,ACTIVE,MONROE PARK CAMPUS,...,2408.10,2408.10,2.0,2017-08-01 00:00:00,NaN,2017-08-01,FY18,0.080270,Energy,Non-Credit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71006,City of Richmond,Gas,NONE,251085-0135800,E&G (UTILITIES),165201,0594,FACILITIES OPERATIONS WEARHOUSE 1,ACTIVE,MCV CAMPUS,...,0.00,0.00,5.0,2024-12-19 00:00:00,2025-01-29 00:00:00,2024-12-19,FY25,NaN,Fixed,Non-Credit
71007,City of Richmond,Gas,NONE,251085-0135800,E&G (UTILITIES),165201,0594,FACILITIES OPERATIONS WEARHOUSE 1,ACTIVE,MCV CAMPUS,...,0.00,0.00,6.0,2024-12-19 00:00:00,2025-01-29 00:00:00,2024-12-19,FY25,NaN,Fixed,Non-Credit
71008,City of Richmond,Gas,NONE,251085-0135800,E&G (UTILITIES),165201,0594,FACILITIES OPERATIONS WEARHOUSE 1,ACTIVE,MCV CAMPUS,...,2956.39,2956.39,7.0,2024-12-19 00:00:00,2025-01-29 00:00:00,2024-12-19,FY25,1.073879,Energy,Non-Credit
71009,City of Richmond,Gas,NONE,251085-0135800,E&G (UTILITIES),165201,0594,FACILITIES OPERATIONS WEARHOUSE 1,ACTIVE,MCV CAMPUS,...,1682.19,1682.19,8.0,2025-01-22 00:00:00,2025-02-03 00:00:00,2025-01-22,FY25,1.117734,Energy,Non-Credit
71010,City of Richmond,Gas,NONE,251085-0135800,E&G (UTILITIES),165201,0594,FACILITIES OPERATIONS WEARHOUSE 1,ACTIVE,MCV CAMPUS,...,1979.76,0.00,9.0,2025-02-21 00:00:00,2025-03-10 00:00:00,2025-02-21,FY25,1.221320,Energy,Non-Credit

In [20]:
counts = (
    valid.groupby(
        ["Account", "Bldg", "Building_Name", "Status", "Campus"]
    )
    .size()
    .reset_index(name="count")
)

counts

,Account,Bldg,Building_Name,Status,Campus,count
0,000085294569,0254,CARY AND BELVIDERE RESIDENTIAL COLLEGE,ACTIVE,MONROE PARK CAMPUS,96
1,000129541108,0254,CARY AND BELVIDERE RESIDENTIAL COLLEGE,ACTIVE,MONROE PARK CAMPUS,96
2,000154224646,0314,ERB ENGINEERING RESEARCH BUILDING,ACTIVE,MONROE PARK CAMPUS,60
3,000206253866,0250,HUMAN RESOURCES BUILDING,ACTIVE,MONROE PARK CAMPUS,96
4,000256453309,0254,CARY AND BELVIDERE RESIDENTIAL COLLEGE,ACTIVE,MONROE PARK CAMPUS,96
...,...,...,...,...,...,...
915,MPC Steam Plant,HGAS,HIBBS-GINTER-ANDERSON-SHAFER ST PLAYHOUSE,ACTIVE,MONROE PARK CAMPUS,8
916,MPC Steam Plant,MPC,MONROE PARK CAMPUS,ACTIVE STEAM,MONROE PARK CAMPUS,8
917,North Branch Steam Line,9500,MCV CAMPUS,ACTIVE,MCV CAMPUS,12
918,North Branch Steam Line,9500,MCV CAMPUS,ACTIVE,MONROE PARK CAMPUS,36
919,North Branch Steam Line,9500,NORTH BRANCH STEAM LINE,ACTIVE,MCV CAMPUS,24

In [22]:
counts_sorted = counts.sort_values(
    ["Account", "Bldg", "count"],
    ascending=[True, True, False]
)

mode_map = counts_sorted.drop_duplicates(["Account", "Bldg"])

mode_map

,Account,Bldg,Building_Name,Status,Campus,count
0,000085294569,0254,CARY AND BELVIDERE RESIDENTIAL COLLEGE,ACTIVE,MONROE PARK CAMPUS,96
1,000129541108,0254,CARY AND BELVIDERE RESIDENTIAL COLLEGE,ACTIVE,MONROE PARK CAMPUS,96
2,000154224646,0314,ERB ENGINEERING RESEARCH BUILDING,ACTIVE,MONROE PARK CAMPUS,60
3,000206253866,0250,HUMAN RESOURCES BUILDING,ACTIVE,MONROE PARK CAMPUS,96
4,000256453309,0254,CARY AND BELVIDERE RESIDENTIAL COLLEGE,ACTIVE,MONROE PARK CAMPUS,96
...,...,...,...,...,...,...
913,MPC Steam Plant,0041,JOHNSON HALL,ACTIVE,MONROE PARK CAMPUS,41
914,MPC Steam Plant,0228,SHAFER COURT DINING CENTER,ACTIVE,MONROE PARK CAMPUS,41
915,MPC Steam Plant,HGAS,HIBBS-GINTER-ANDERSON-SHAFER ST PLAYHOUSE,ACTIVE,MONROE PARK CAMPUS,8
916,MPC Steam Plant,MPC,MONROE PARK CAMPUS,ACTIVE STEAM,MONROE PARK CAMPUS,8
918,North Branch Steam Line,9500,MCV CAMPUS,ACTIVE,MONROE PARK CAMPUS,36

In [25]:
# Drop any leftover mode columns from earlier attempts
mode_cols = [c for c in df.columns if c.endswith("_mode")]
df = df.drop(columns=mode_cols, errors="ignore")

df.columns[df.columns.str.endswith("_mode")]

Index([], dtype='str')

In [26]:
df = df.merge(
    mode_map[["Account", "Bldg", "Building_Name", "Status", "Campus"]],
    on=["Account", "Bldg"],
    how="left",
    suffixes=("", "_mode")
)

In [27]:
missing_mask = df["Building_Name"].isna()

df.loc[missing_mask, "Building_Name"] = df.loc[missing_mask, "Building_Name_mode"]
df.loc[missing_mask, "Status"] = df.loc[missing_mask, "Status_mode"]
df.loc[missing_mask, "Campus"] = df.loc[missing_mask, "Campus_mode"]

df = df.drop(columns=["Building_Name_mode", "Status_mode", "Campus_mode"])

In [29]:
df[df["Building_Name"].isna()][["Account","Bldg","Status","Campus"]].head(20)

             Account  Bldg Status Campus
813     008454937502  7013    NaN    NaN
827     008454937502  7013    NaN    NaN
872     008454937502  7013    NaN    NaN
888     008454937502  7013    NaN    NaN
918     008454937502  7013    NaN    NaN
948     008454937502  7013    NaN    NaN
988     001916719204   NaN    NaN    NaN
1004    001925133439   NaN    NaN    NaN
1110    001925133439   NaN    NaN    NaN
1343    001925133439   NaN    NaN    NaN
1372    001925133439   NaN    NaN    NaN
1602    001925133439   NaN    NaN    NaN
1647    001925133439   NaN    NaN    NaN
1693  250435-0010531   NaN    NaN    NaN
1747  250435-0010531   NaN    NaN    NaN
1978  250435-0010531   NaN    NaN    NaN
2711    006911596580   NaN    NaN    NaN
2712    006911596580   NaN    NaN    NaN
3129    006911596580   NaN    NaN    NaN
3130    006911596580   NaN    NaN    NaN

In [30]:
# account-level mode map for rows that have valid Building_Name
valid2 = df[df["Building_Name"].notna()].copy()

acct_counts = (
    valid2.groupby(["Account", "Building_Name", "Status", "Campus"])
          .size()
          .reset_index(name="count")
)

acct_counts = acct_counts.sort_values(
    ["Account", "count"],
    ascending=[True, False]
)

acct_mode_map = acct_counts.drop_duplicates(["Account"])[
    ["Account", "Building_Name", "Status", "Campus"]
].rename(columns={
    "Building_Name": "Building_Name_acct",
    "Status": "Status_acct",
    "Campus": "Campus_acct"
})

In [31]:
# merge account-level fallback
df = df.merge(acct_mode_map, on="Account", how="left")

still_missing = df["Building_Name"].isna()

df.loc[still_missing, "Building_Name"] = df.loc[still_missing, "Building_Name_acct"]
df.loc[still_missing, "Status"] = df.loc[still_missing, "Status_acct"]
df.loc[still_missing, "Campus"] = df.loc[still_missing, "Campus_acct"]

# drop helper columns
df = df.drop(columns=["Building_Name_acct", "Status_acct", "Campus_acct"])

In [32]:
df[df["Building_Name"].isna()][["Account", "Bldg"]].drop_duplicates()

            Account  Bldg
813    008454937502  7013
5554     DIFFERENCE   NaN
7377   004062953916   NaN
71011           NaN   NaN

In [33]:
problem_keys = [
    ("008454937502", 7013),
    ("DIFFERENCE", np.nan),
    ("004062953916", np.nan),
]

df[
    (df["Account"].isin(["008454937502", "DIFFERENCE", "004062953916"])) |
    (df["Account"].isna())
]

,Provider,Type,Operator,Account,Customer_Type,Index,Bldg,Building_Name,Status,Campus,...,Amount_Due,Total_Usage,Reporting_Month,Svc_End_Date,UtiliTrak_Date,Svc_End_Date_Fixed,FY,Cost_per_kwh,Charge_Type,Bill_Type
813,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,258.14,258.14,2.0,2019-08-01 00:00:00,NaN,2019-08-01,FY20,0.091996,Energy,Non-Credit
827,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,285.94,285.94,4.0,2019-10-01 00:00:00,NaN,2019-10-01,FY20,0.093019,Energy,Non-Credit
872,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,352.37,352.37,6.0,2019-12-01 00:00:00,NaN,2019-12-01,FY20,0.089684,Energy,Non-Credit
888,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,335.85,335.85,8.0,2020-02-01 00:00:00,NaN,2020-02-01,FY20,0.090501,Energy,Non-Credit
918,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,282.43,282.43,10.0,2020-04-01 00:00:00,NaN,2020-04-01,FY20,0.094648,Energy,Non-Credit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit

In [34]:
df[(df["Account"] == "008454937502")]

,Provider,Type,Operator,Account,Customer_Type,Index,Bldg,Building_Name,Status,Campus,...,Amount_Due,Total_Usage,Reporting_Month,Svc_End_Date,UtiliTrak_Date,Svc_End_Date_Fixed,FY,Cost_per_kwh,Charge_Type,Bill_Type
813,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,258.14,258.14,2.0,2019-08-01 00:00:00,NaN,2019-08-01,FY20,0.091996,Energy,Non-Credit
827,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,285.94,285.94,4.0,2019-10-01 00:00:00,NaN,2019-10-01,FY20,0.093019,Energy,Non-Credit
872,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,352.37,352.37,6.0,2019-12-01 00:00:00,NaN,2019-12-01,FY20,0.089684,Energy,Non-Credit
888,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,335.85,335.85,8.0,2020-02-01 00:00:00,NaN,2020-02-01,FY20,0.090501,Energy,Non-Credit
918,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,282.43,282.43,10.0,2020-04-01 00:00:00,NaN,2020-04-01,FY20,0.094648,Energy,Non-Credit
948,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,262.82,262.82,12.0,2020-06-01 00:00:00,NaN,2020-06-01,FY20,0.088971,Energy,Non-Credit
4325,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,198.61,198.61,1.0,2017-07-01 00:00:00,NaN,2017-07-01,FY18,0.089950,Energy,Non-Credit
4326,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,223.86,223.86,2.0,2017-08-01 00:00:00,NaN,2017-08-01,FY18,0.094019,Energy,Non-Credit
4327,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,170.60,170.60,3.0,2017-09-01 00:00:00,NaN,2017-09-01,FY18,0.077758,Energy,Non-Credit
4328,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,274.80,274.80,4.0,2017-10-01 00:00:00,NaN,2017-10-01,FY18,0.095284,Energy,Non-Credit
4329,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,183.96,183.96,5.0,2017-11-01 00:00:00,NaN,2017-11-01,FY18,0.097230,Energy,Non-Credit
4330,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,268.07,268.07,6.0,2017-12-01 00:00:00,NaN,2017-12-01,FY18,0.095773,Energy,Non-Credit
4331,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,413.32,413.32,7.0,2018-01-01 00:00:00,NaN,2018-01-01,FY18,0.089174,Energy,Non-Credit
4332,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,422.14,422.14,8.0,2018-02-01 00:00:00,NaN,2018-02-01,FY18,0.089172,Energy,Non-Credit
4333,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,405.14,405.14,9.0,2018-03-01 00:00:00,NaN,2018-03-01,FY18,0.090011,Energy,Non-Credit
4334,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,453.07,453.07,10.0,2018-04-01 00:00:00,NaN,2018-04-01,FY18,0.087821,Energy,Non-Credit
4335,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,333.53,333.53,11.0,2018-05-01 00:00:00,NaN,2018-05-01,FY18,0.092802,Energy,Non-Credit
4336,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,300.85,300.85,12.0,2018-06-01 00:00:00,NaN,2018-06-01,FY18,0.094074,Energy,Non-Credit
5073,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,0.00,0.00,11.0,2021-05-01 00:00:00,NaN,2021-05-01,FY21,NaN,Fixed,Non-Credit
10893,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,283.83,283.83,1.0,2018-07-01 00:00:00,NaN,2018-07-01,FY19,0.095533,Energy,Non-Credit
10894,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,321.52,321.52,2.0,2018-08-01 00:00:00,NaN,2018-08-01,FY19,0.090928,Energy,Non-Credit
10895,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,303.35,303.35,3.0,2018-09-01 00:00:00,NaN,2018-09-01,FY19,0.092288,Energy,Non-Credit
10896,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,319.45,319.45,4.0,2018-10-01 00:00:00,NaN,2018-10-01,FY19,0.090804,Energy,Non-Credit
10897,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,332.29,332.29,5.0,2018-11-01 00:00:00,NaN,2018-11-01,FY19,0.089639,Energy,Non-Credit
10898,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,359.03,359.03,6.0,2018-12-01 00:00:00,NaN,2018-12-01,FY19,0.089134,Energy,Non-Credit
10899,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,382.37,382.37,7.0,2019-01-01 00:00:00,NaN,2019-01-01,FY19,0.086607,Energy,Non-Credit
10900,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,329.27,329.27,8.0,2019-02-01 00:00:00,NaN,2019-02-01,FY19,0.087039,Energy,Non-Credit
10901,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,317.57,317.57,9.0,2019-03-01 00:00:00,NaN,2019-03-01,FY19,0.086982,Energy,Non-Credit
10902,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,311.29,311.29,10.0,2019-04-01 00:00:00,NaN,2019-04-01,FY19,0.087490,Energy,Non-Credit
10903,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,291.39,291.39,11.0,2019-05-01 00:00:00,NaN,2019-05-01,FY19,0.091031,Energy,Non-Credit
10904,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,274.95,274.95,12.0,2019-06-01 00:00:00,NaN,2019-06-01,FY19,0.092420,Energy,Non-Credit
12983,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,285.78,285.78,11.0,2020-05-01 00:00:00,NaN,2020-05-01,FY20,0.094348,Energy,Non-Credit
13121,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,285.52,285.52,1.0,2019-07-01 00:00:00,NaN,2019-07-01,FY20,0.092762,Energy,Non-Credit
13219,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,277.58,277.58,9.0,2020-03-01 00:00:00,NaN,2020-03-01,FY20,0.094705,Energy,Non-Credit
21405,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,0.00,0.00,12.0,2021-06-01 00:00:00,NaN,2021-06-01,FY21,NaN,Fixed,Non-Credit
23338,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,294.65,294.65,3.0,2019-09-01 00:00:00,NaN,2019-09-01,FY20,0.085879,Energy,Non-Credit
23394,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,292.57,292.57,5.0,2019-11-01 00:00:00,NaN,2019-11-01,FY20,0.092381,Energy,Non-Credit
23677,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,355.14,355.14,7.0,2020-01-01 00:00:00,NaN,2020-01-01,FY20,0.089546,Energy,Non-Credit
31472,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,101.83,115.63,10.0,2021-04-01 00:00:00,NaN,2021-04-01,FY21,0.099541,Energy,Non-Credit
31563,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,216.75,216.75,1.0,2020-07-01 00:00:00,NaN,2020-07-01,FY21,0.090050,Energy,Non-Credit
31564,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,226.67,226.67,2.0,2020-08-01 00:00:00,NaN,2020-08-01,FY21,0.090271,Energy,Non-Credit
31565,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,247.59,247.59,3.0,2020-09-01 00:00:00,NaN,2020-09-01,FY21,0.089383,Energy,Non-Credit
31566,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,268.70,268.70,4.0,2000-10-01 00:00:00,NaN,2020-10-01,FY21,0.093689,Energy,Non-Credit
31567,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,208.16,208.16,5.0,2020-11-01 00:00:00,NaN,2020-11-01,FY21,0.094747,Energy,Non-Credit
31568,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,245.17,245.17,6.0,2020-12-01 00:00:00,NaN,2020-12-01,FY21,0.093719,Energy,Non-Credit
31569,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,252.83,252.83,7.0,2021-01-01 00:00:00,NaN,2021-01-01,FY21,0.093571,Energy,Non-Credit
31570,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,230.54,230.54,8.0,2021-02-01 00:00:00,NaN,2021-02-01,FY21,0.093868,Energy,Non-Credit
31571,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,108.29,108.29,9.0,2021-03-01 00:00:00,NaN,2021-03-01,FY21,0.098895,Energy,Non-Credit
39597,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,216.75,216.75,1.0,2021-07-01 00:00:00,NaN,2021-07-01,FY22,0.090050,Energy,Non-Credit
39598,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,2.0,2021-08-01 00:00:00,NaN,2021-08-01,FY22,NaN,Fixed,Non-Credit
39599,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,3.0,2021-09-01 00:00:00,NaN,2021-09-01,FY22,NaN,Fixed,Non-Credit
39600,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,4.0,2021-10-01 00:00:00,NaN,2021-10-01,FY22,NaN,Fixed,Non-Credit
39601,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,5.0,2021-11-01 00:00:00,NaN,2021-11-01,FY22,NaN,Fixed,Non-Credit
39602,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,6.0,2021-12-01 00:00:00,NaN,2021-12-01,FY22,NaN,Fixed,Non-Credit
39603,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,7.0,2022-01-01 00:00:00,NaN,2022-01-01,FY22,NaN,Fixed,Non-Credit
39604,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,8.0,2022-02-01 00:00:00,NaN,2022-02-01,FY22,NaN,Fixed,Non-Credit
39605,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,9.0,2022-03-01 00:00:00,NaN,2022-03-01,FY22,NaN,Fixed,Non-Credit
39606,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,10.0,2022-04-01 00:00:00,NaN,2022-04-01,FY22,NaN,Fixed,Non-Credit
39607,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,11.0,2022-05-01 00:00:00,NaN,2022-05-01,FY22,NaN,Fixed,Non-Credit
39608,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,NaN,0.00,12.0,2022-06-01 00:00:00,NaN,2022-06-01,FY22,NaN,Fixed,Non-Credit

In [37]:
df[df["Building_Name"].isna()][["Account", "Bldg"]].drop_duplicates()

            Account  Bldg
813    008454937502  7013
5554     DIFFERENCE   NaN
7377   004062953916   NaN
71011           NaN   NaN

In [39]:
flagged_rows = df[df["Building_Name"].isna()].copy()
flagged_rows

,Provider,Type,Operator,Account,Customer_Type,Index,Bldg,Building_Name,Status,Campus,...,Amount_Due,Total_Usage,Reporting_Month,Svc_End_Date,UtiliTrak_Date,Svc_End_Date_Fixed,FY,Cost_per_kwh,Charge_Type,Bill_Type
813,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,258.14,258.14,2.0,2019-08-01 00:00:00,NaN,2019-08-01,FY20,0.091996,Energy,Non-Credit
827,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,285.94,285.94,4.0,2019-10-01 00:00:00,NaN,2019-10-01,FY20,0.093019,Energy,Non-Credit
872,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,352.37,352.37,6.0,2019-12-01 00:00:00,NaN,2019-12-01,FY20,0.089684,Energy,Non-Credit
888,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,335.85,335.85,8.0,2020-02-01 00:00:00,NaN,2020-02-01,FY20,0.090501,Energy,Non-Credit
918,DVP,Electric,NONE,008454937502,AUXILIARY,323414,7013,NaN,NaN,NaN,...,282.43,282.43,10.0,2020-04-01 00:00:00,NaN,2020-04-01,FY20,0.094648,Energy,Non-Credit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit
1048569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,Fixed,Non-Credit

In [40]:
flagged_rows[["Account", "Bldg"]].drop_duplicates()

            Account  Bldg
813    008454937502  7013
5554     DIFFERENCE   NaN
7377   004062953916   NaN
71011           NaN   NaN

In [41]:
df_clean = df[df["Building_Name"].notna()].copy()

In [42]:
df_clean["Building_Name"].isna().sum()

np.int64(0)

In [43]:
import os

analysis_path = r"C:\Users\terzi\Desktop\BI Dashboard FY19-25\analysis"

os.makedirs(analysis_path, exist_ok=True)

analysis_path

'C:\\Users\\terzi\\Desktop\\BI Dashboard FY19-25\\analysis'

In [45]:
flagged_rows.to_csv(
    r"C:\Users\terzi\Desktop\BI Dashboard FY19-25\analysis\utility_flagged_rows.csv",
    index=False
)

df_clean.to_csv(
    r"C:\Users\terzi\Desktop\BI Dashboard FY19-25\analysis\utility_clean_for_EDA.csv",
    index=False
)